feat: add loader component
trimble-oss/modus-wc-2.0 pull request #84
Opened 2024-12-06 20:03 UTC by stuart-rimel

### :page_facing_up: Summary of Changes

Adds loader component. Exposes color, size, and variant animation as props to users. 

I ran into issues with tailwindcss minification encoding for Daisy's embedded svg data, so I've added those to `modus-wc-loader.scss` under our own class names (see [styles](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/loading.css) for their [loading component](https://daisyui.com/components/loading/)). 

Accessibility: 
- `aria-label` required
- `role` set to `status`
- `tabindex` set to `-1`

### :thought_balloon: Type of Change

- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [ ] Other

### :clipboard: Test Plan

Snapshot testing, manually tested in storybook. 

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [x] My code is clean and readable
- [x] I followed standard conventions
- [x] Component code is WCAG 2.2 compliant (if applicable)
- [ ] I have made theme files changes (if applicable)
- [ ] I have made documentation changes (if applicable)
- [ ] I have made Storybook changes including usage documentation (if applicable)
- [x] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Azure DevOps Work Item

[AB#577746](https://dev.azure.com/ViewpointVSO/74194628-0b6e-4b03-95a4-2d06c069dcbe/_workitems/edit/577746)

2024-12-06 21:49 UTC, gabriel-piltzer-trimble requested changes

2024-12-06 21:49 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-loader/modus-wc-loader.tailwind.ts
> +    classes = `${classes} modus-wc-loader-${props.color}`;
I would have expected all of these to have been added under `src/styles/tailwind-themeable.scss` so they'd be included during the Tailwind purge process.

2024-12-06 21:49 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-loader/modus-wc-loader.spec.ts
> +      html: '<modus-wc-loader aria-label="Loading loader" custom-class="test-class" size="lg" variant="dots"></modus-wc-loader>',
Should we test `color` here as well?

2024-12-06 21:49 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-loader/modus-wc-loader.scss
> +  &.modus-wc-loader-ball {
Curious if we should apply these outside of the data-theme styling. Otherwise will they apply to other themes automatically?

2024-12-06 21:49 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-loader/modus-wc-loader.scss
Make sure we style theme specific things within the data-theme block, and things that everybody will need outside of them.

2024-12-06 21:49 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-loader/modus-wc-loader.stories.ts
> +export const Default: Story = {
Curious if we should demo all variants

2024-12-06 21:49 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-loader/modus-wc-loader.stories.ts
> +    layout: 'padded',
Does this component require this?

2024-12-06 22:38 UTC, stuart-rimel commented on src/components/atoms/modus-wc-loader/modus-wc-loader.stories.ts
> +    layout: 'padded',
nope it is not 🙃, removed in updated PR

2024-12-06 22:56 UTC, stuart-rimel commented on src/components/atoms/modus-wc-loader/modus-wc-loader.stories.ts
> +export const Default: Story = {
Added loader story variants in updated PR

2024-12-06 23:35 UTC, stuart-rimel commented on src/components/atoms/modus-wc-loader/modus-wc-loader.tailwind.ts
> +    classes = `${classes} modus-wc-loader-${props.color}`;
These are not tailwindcss classes. Had to create our own which are defined within `modus-wc-loader.scss` and use the values from [daisy's loading component styles](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/loading.css). This was a workaround from tailwind minification issues with this specific component. However, it does seem like we could get away with just using the daisy ui classes for loading color and size since those don't have any gross embedded svg data, Would you prefer I use those instead?

2024-12-06 23:38 UTC, stuart-rimel commented on src/components/atoms/modus-wc-loader/modus-wc-loader.scss
> +  &.modus-wc-loader-ball {
I removed the data-theme selectors from `modus-wc-loader.scss` in the updated PR.

2024-12-06 23:39 UTC, stuart-rimel commented on src/components/atoms/modus-wc-loader/modus-wc-loader.scss
https://github.com/Trimble-Construction/modus-wc-2.0/pull/84#discussion_r1874130325

2024-12-06 23:45 UTC, stuart-rimel commented on src/components/atoms/modus-wc-loader/modus-wc-loader.spec.ts
> +      html: '<modus-wc-loader aria-label="Loading loader" custom-class="test-class" size="lg" variant="dots"></modus-wc-loader>',
fixed

2024-12-06 23:48 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-loader/modus-wc-loader.tailwind.ts
> +    classes = `${classes} modus-wc-loader-${props.color}`;
Yes I would use the Daisy classes when we can. If we're going to invent our own, I recommend BEM naming `modus-wc-loader--big`

2024-12-07 00:43 UTC, gabriel-piltzer-trimble submitted a review, later dismissed

2024-12-07 00:50 UTC, gabriel-piltzer-trimble approved these changes

2024-12-07 00:50 UTC, merged