feat: add menu and autocomplete components
trimble-oss/modus-wc-2.0 pull request #86
Opened 2024-12-09 19:46 UTC by gabriel-piltzer-trimble

### :page_facing_up: Summary of Changes

This PR adds 2 new components:
- `modus-wc-menu`
- `modus-wc-autocomplete`

It resolves an event timing issue with `onChange` bindings by updating them to `onInput`. This makes it event as the user types, instead of when they leave the input.

Type names have been updated to help differentiate sizes between DaisyUI and Modus.

The core files for this PR are located under:
- `src/components/atoms/modus-wc-menu`
- `src/components/molecules/modus-wc-autocomplete`

### :thought_balloon: Type of Change

- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [ ] Other

### :clipboard: Test Plan

Unit tests updated and added

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [x] My code is clean and readable
- [x] I followed standard conventions
- [x] Component code is WCAG 2.2 compliant (if applicable)
- [x] I have made theme files changes (if applicable)
- [ ] I have made documentation changes (if applicable)
- [x] I have made Storybook changes including usage documentation (if applicable)
- [x] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Azure DevOps Work Item

[AB#578575](https://dev.azure.com/ViewpointVSO/74194628-0b6e-4b03-95a4-2d06c069dcbe/_workitems/edit/578575)

2024-12-09 22:38 UTC, stuart-rimel requested changes
Both of these components look good and I like the refactoring of modus vs daisy types along with the event change to 'onInput'

Just left a few comments for you

2024-12-09 22:38 UTC, stuart-rimel commented on src/components/atoms/modus-wc-menu/modus-wc-menu.stories.ts
> +        .items=${ifDefined(args.items)}
`ifDefined` directive has no effect here when using property binding syntax '.'

```suggestion
        .items=${args.items}
```

2024-12-09 22:38 UTC, stuart-rimel commented on src/components/atoms/modus-wc-menu/modus-wc-menu.tsx
> +  };
just curious, should we also set active item to what they selected? 

Currently when testing in storybook I'm not able to set any of the menu items to 'active' through clicking alone

2024-12-09 22:38 UTC, stuart-rimel commented on src/components/atoms/modus-wc-menu/modus-wc-menu.stories.ts
> +export const ItemVariations: Story = {
I'm getting contrast accessibility violations from this story:
`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds`

2024-12-09 22:38 UTC, stuart-rimel commented on src/components/molecules/modus-wc-autocomplete/modus-wc-autocomplete.scss
> +}
Remove unused css class

2024-12-09 22:38 UTC, stuart-rimel commented on src/components/molecules/modus-wc-autocomplete/modus-wc-autocomplete.tsx
> +    // const propClasses = convertPropsToClasses();
If you think we'll give this component another pass and potentially use this then I'd say keep it, otherwise probably best to delete this and the empty autocomplete tailwind file

2024-12-09 23:38 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-menu/modus-wc-menu.tsx
> +  };
I would expect the user to do this and set the prop for `activeItemValue` which will then highlight the item. Remember the React controlled input/component pattern.

2024-12-09 23:38 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-menu/modus-wc-menu.tsx
> +  };
I could do it in Storybook as part of the demo if you think it would be valuable

2024-12-09 23:48 UTC, stuart-rimel commented on src/components/atoms/modus-wc-menu/modus-wc-menu.tsx
> +  };
Yeah I think showing an example of that would be useful, thanks!

2024-12-10 15:38 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-menu/modus-wc-menu.stories.ts
> +export const ItemVariations: Story = {
I see the violation, these are the colors specified in Figma by Modus. I will review violations with Mitch and we'll update the colors at that time.
@mitch-trimble 

I have also created user story [579315](https://dev.azure.com/ViewpointVSO/Prism/_workitems/edit/579315) to follow up on all A11Y issues.

2024-12-10 15:40 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-menu/modus-wc-menu.stories.ts
> +        .items=${ifDefined(args.items)}
Updated

2024-12-10 15:40 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-menu/modus-wc-menu.tsx
> +  };
Added activeItemValue to main component demo

2024-12-10 15:41 UTC, gabriel-piltzer-trimble commented on src/components/molecules/modus-wc-autocomplete/modus-wc-autocomplete.scss
> +}
Removed

2024-12-10 15:42 UTC, gabriel-piltzer-trimble commented on src/components/molecules/modus-wc-autocomplete/modus-wc-autocomplete.tsx
> +    // const propClasses = convertPropsToClasses();
Removed (great call)

2024-12-10 17:05 UTC, stuart-rimel commented on src/components/atoms/modus-wc-menu/modus-wc-menu.stories.ts
> +export const ItemVariations: Story = {
sounds good, thanks

2024-12-10 17:13 UTC, stuart-rimel approved these changes

2024-12-10 17:15 UTC, merged