feat: add time input
trimble-oss/modus-wc-2.0 pull request #88
Opened 2024-12-14 01:59 UTC by stuart-rimel

### :page_facing_up: Summary of Changes

Adds the time input component.

This component is pretty much just the native `<input type="time">` component with a couple of abstractions on top.
1. `seconds` prop as a boolean for controlling whether the seconds field is displayed within the component. This internally sets the `step` attribute to 1.
2. `timeOptions` prop which takes a list of time strings in the format `HH:mm`, `HH:mm:ss`. This internally sets the `list` attribute to point to an internally generated `<datalist>` element.

There are two types of dropdowns that come with the native `<input type="time">`, one is the default which allows users to select the time for each field. The other dropdown is the `<datalist>` that is supplied by either `timeOptions` or the `list` id of a `<datalist>` element on the same document. When both `timeOptions` and `list` are provided, the `<datalist>` which `list` points to will take precedence. [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#list) for more on using `list` with this input. 

This PR also removes the `autoFocus` prop from the date, number, select, and text inputs.

### :thought_balloon: Type of Change

- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [ ] Other

### :clipboard: Test Plan

Manually tested in storybook, included unit tests for 100% coverage.

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [x] My code is clean and readable
- [x] I followed standard conventions
- [x] Component code is WCAG 2.2 compliant (if applicable)
- [ ] I have made theme files changes (if applicable)
- [ ] I have made documentation changes (if applicable)
- [ ] I have made Storybook changes including usage documentation (if applicable)
- [ ] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Azure DevOps Work Item

[AB#578576](https://dev.azure.com/ViewpointVSO/74194628-0b6e-4b03-95a4-2d06c069dcbe/_workitems/edit/578576)

2024-12-16 20:39 UTC, gabriel-piltzer-trimble requested changes

2024-12-16 20:39 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +const INTERNAL_DATALIST_NAME = 'modus-wc-internal-time-options';
What's the value of having this constant outside of the component?

2024-12-16 20:39 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  @Prop() seconds?: boolean = false;
The naming on this isn't shouting `boolean`. Did you consider other names? Initially I thought `seconds` would be of type `number`.

2024-12-16 20:39 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  @Prop() timeOptions: string[] = [];
Would `datalistOptions` make more sense to align with HTML naming?

2024-12-16 20:39 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  @Prop({ mutable: true }) list?: string;
Would `datalistId` make more sense based on the comment?

2024-12-16 20:39 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  private readonly internalDatalistId = `${INTERNAL_DATALIST_NAME}-${Math.random().toString(36).substring(2, 11)}`;
I recommend using `crypto.randomUUID()` or `nanoid` over custom logic

2024-12-16 20:39 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  /**
Be consistent with comment formatting. For internal object use `//`

2024-12-16 20:39 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.scss
> +.modus-wc-input {
This styling block should include both `data-theme` selectors, when not using these themes the components should look like DaisyUI (not Modus).

2024-12-16 20:41 UTC, gabriel-piltzer-trimble commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +          step={this.step || !!this.seconds ? 1 : 60}
```suggestion
          step={this.step || this.seconds ? 1 : 60}
```

Does this work?

2024-12-17 00:03 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  /**
fixed

2024-12-17 00:05 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  private readonly internalDatalistId = `${INTERNAL_DATALIST_NAME}-${Math.random().toString(36).substring(2, 11)}`;
Great suggestions! I really like `nanoid` so I went that direction which led to me to adding `nanoid` as a dependency. See updated PR.

2024-12-17 00:05 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  @Prop({ mutable: true }) list?: string;
Love it, renamed in updated PR

2024-12-17 00:06 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  @Prop() timeOptions: string[] = [];
I like that, fixed in updated PR

2024-12-17 00:10 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  @Prop() seconds?: boolean = false;
Good point! I renamed this prop to be `showSeconds` in latest change set. Lmk what you think

2024-12-17 00:14 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +const INTERNAL_DATALIST_NAME = 'modus-wc-internal-time-options';
Definitely awkward. I refactored this name to be inlined during `insternalDatalistId` instantiation.
```ts
private readonly internalDatalistId = `${'modus-wc-datalist-id'}-${nanoid(10)}`;
```
Happy to refactor again if you'd prefer to still use a constant

2024-12-17 00:24 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.scss
> +.modus-wc-input {
Nice catch, fixed in Updated PR

2024-12-17 00:25 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +          step={this.step || !!this.seconds ? 1 : 60}
fixed in updated PR

2024-12-17 17:49 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  private readonly internalDatalistId = `${INTERNAL_DATALIST_NAME}-${Math.random().toString(36).substring(2, 11)}`;
UPDATE: 

@gabriel-piltzer-trimble turns out I ran into major issues with jest and nanoid ESM modules. I tried configuring  `transformIgnorePatterns` in our stencil config, but still encountered the same unexpected token error from jest. I also tried mocking the module in a setup test file but got the same error back again. I'm only able to get jest to work with v3 of nanoid (they're on v5 currently). 

Going to try this again using `crypto.randomUUID()`

2024-12-17 22:00 UTC, stuart-rimel commented on src/components/atoms/modus-wc-time-input/modus-wc-time-input.tsx
> +  private readonly internalDatalistId = `${INTERNAL_DATALIST_NAME}-${Math.random().toString(36).substring(2, 11)}`;
UPDATE 2:

Per our conversation today I've reverted this back to using the Math.random method but it's now in a utils file for generic use amongst our components

2024-12-17 22:10 UTC, gabriel-piltzer-trimble commented on angular-value-accessor-bindings.ts
> +      'modus-wc-time-input',
Alpha sort

2024-12-17 22:12 UTC, stuart-rimel commented on angular-value-accessor-bindings.ts
> +      'modus-wc-time-input',
fixed

2024-12-17 22:31 UTC, gabriel-piltzer-trimble approved these changes

2024-12-17 22:35 UTC, merged